{"tests": [{"data": {"status": "failure", "inputs": {"input": {"src": "hda", "id": "2891970512fa2d5a"}, "tree": {"src": "hda", "id": "5729865256bc2525"}, "represent": "all"}, "problem_type": "exceptions.AssertionError", "problem_log": "Traceback (most recent call last):\n  File \"/opt/6.x/python-2.7.2/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n  File \"/tmp/tmptLwhcx/galaxy-dev/test/functional/test_toolbox.py\", line 316, in test_tool\n    self.do_it(td)\n  File \"/tmp/tmptLwhcx/galaxy-dev/test/functional/test_toolbox.py\", line 75, in do_it\n    self.assertTrue(data_list or data_collection_list)\n  File \"/opt/6.x/python-2.7.2/lib/python2.7/unittest/case.py\", line 420, in assertTrue\n    raise self.failureException(msg)\nAssertionError: {} is not true\n"}, "id": "functional.test_toolbox.TestForTool_hmadaptsearch.test_tool_000000", "has_data": true}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 0, "num_failures": 1, "num_tests": 1}}